version: "3.7"
services:
  backend:
    depends_on:
      - db
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    expose:
      - 1337
    volumes:
      - ./app:/srv/app
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "portfolio"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "rootroot"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
